### ISSUE TITLE
[MODULO] bedtools/genomecov

### ISSUE THREAD

**Issue by yocra3** [CIBERER/GdTBioinfo-nf-cnvs#16]
## Descripción del programa

Implementar función genomecov del programa bedtools (https://bedtools.readthedocs.io/en/latest/)

## Parámetros

Ninguno. 

## Inputs 

- Lista de archivos con rangos genómicas (p.e. output de #14)
 
## Outputs

- Archivo txt con el coverage por región.

**Comment by RojoCarrillo** [comment]
Pull request #69
