### ISSUE TITLE
[MODULO] bedtools/intersect

### ISSUE THREAD

**Issue by yocra3** [CIBERER/GdTBioinfo-nf-cnvs#17]
## Descripción del programa

Implementar función intersect del programa bedtools (https://bedtools.readthedocs.io/en/latest/)

## Parámetros

Ninguno.

## Inputs 

- tupla id, archivo bed
- archivo bed

## Outputs

- tupla id, archivo bed (rangos que no interseccionan)

**Comment by RojoCarrillo** [comment]
Pull request #68
