### ISSUE TITLE
[MODULO] bedtools/subtract

### ISSUE THREAD

**Issue by yocra3** [CIBERER/GdTBioinfo-nf-cnvs#25]
## Descripción del programa

Implementar la función subtract de bedtools (https://bedtools.readthedocs.io/en/latest/content/tools/subtract.html).

## Parámetros

Ninguno

## Inputs 

- tupla id, bed1, bed2

## Outputs

- tupla id, bed (Después del filtrado)

**Comment by RojoCarrillo** [comment]
He creado el pull request, como he comentado había cosas que no estaban del todo claras y de hecho ha creado una carpeta automáticamente al importar el módulo.

**Comment by RojoCarrillo** [comment]
pull request #66
